apiVersion: v1
kind: Service
metadata:
  name: room-booking-service
spec:
  type: NodePort
  selector:
    app: room-booking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30080 # Optional: You can specify a fixed port or let K8s assign one
